version: '3.3'
services:
  mysql:
    image: mysql:5.7
    ports: ['3333:3306']
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

  php:
    build: docker/php-fpm
    ports: ['9000:9000']
    volumes: ['./symfony/:/var/www/symfony:cached']

  nginx:
    build: ./docker/nginx
    ports: ['8001:80']
    volumes: ['./symfony/:/var/www/symfony:cached']
