version: '3'
services:
  mysql:
    image: mysql:5.7
    ports: ['3333:3306']

    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

  php:
    build: docker/php-fpm
    ports: ['9000:9000']
    volumes: ['./symfony/:/var/www/symfony:cached']

  nginx:
    build: ./docker/nginx
    ports: ['8001:80']
    volumes: ['./symfony/:/var/www/symfony:cached']
